Fix multiple keyup event handlers
sillsdev/web-languageforge pull request #1174
Opened 2021-09-28 03:09 UTC by rmunn

TODO: Edit this description.

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

### Type of Change

Only keep lines below that describe this change, then delete the rest.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- migration required (a model change requiring a mongodb script or migration script)
- UI change

## Screenshots

Please provide screenshots / animations for any change that involves the UI.  Please provide animations to demonstrate user interaction / behavior changes

## How Has This Been Tested?

Please describe the manual tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the title/description of this PR which will be used as the squashed PR commit message
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-09-28 08:07 UTC, megahirt commented
It's not clear to me how these changes result in a single keyup event handler.

2021-09-29 14:56 UTC, longrunningprocess commented
@palmtreefrb the following code give us what we want I believe.  A couple of important points, it switches the listener to capture mode, it prevents the container from scrolling and it is done on `keydown`:

```javascript
window.addEventListener('keydown', e => {
	if (isPagingKey(e.key)) {
		console.log(`keydown (capture/preventDefault): ${e.key}`)
		e.preventDefault()
	} 
}, true)
```

let me know if you'd like to discuss it more, this is the vanilla js way to do it, we'll need to translate it into ng.

2021-09-29 17:09 UTC, longrunningprocess commented
You can disregard this comment here, it seems to be off-topic a bit.  I've opened other issues that are related to what this provided code was intended to solve (#1177 ).

2021-09-30 09:30 UTC, megahirt requested changes
this PR is superseded by #1182 and should be closed once 1182 is merged.

2021-09-30 13:16 UTC, megahirt commented
This PR has been superseded by #1182 so will not merge.

2021-09-30 13:16 UTC, closed without merging