Preliminary QA deployment runtime
sillsdev/web-languageforge pull request #895
Opened 2021-03-26 18:42 UTC by longrunningprocess

This will give us a running QA env (behind a VPN) that accomplishes the following:

- site is up
- email/pw authn is functional
- db updates occur
- email is sent

further changes will be required as a result of #893 depending upon merge timing.

2021-04-01 08:17 UTC, megahirt requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/895)* status: all files reviewed, 5 unresolved discussions (waiting on @longrunningprocess)

___
*[.github/workflows/build-and-deploy-images.yml, line 7 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX00qQf-63rMWrzOtKT:-MX00qQf-63rMWrzOtKU:b-7o31o1) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L7)):*
> ```YAML
>   push:
>     branches:
>       - 'chore/docker-deployment'
> ```

we'll want to change this to be `qa` and `live` since these two branches track our production deployments.  Good that you've been testing GA using your PR branch.  Looks like it's working well!.  If you'd prefer to change this after your PR is merged, that is fine with me.
___
*[.github/workflows/build-and-deploy-images.yml, line 49 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01c3D8bUNOJy_yE35:-MX01c3E75XYevEOpjDw:b-irw494) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L49)):*
> ```YAML
>         run: |
>           docker tag lf-app sillsdev/web-languageforge:app-latest
>           docker tag wait sillsdev/web-languageforge:wait-latest
> ```

Do we need to have this line now that the wait image is already published?
___
*[.github/workflows/build-and-deploy-images.yml, line 63 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01jns5rhVVFN4WWUk:-MX01jns5rhVVFN4WWUl:b-irw494) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L63)):*
> ```YAML
>         run: |
>           docker push sillsdev/web-languageforge:app-latest
>           docker push sillsdev/web-languageforge:wait-latest
> ```

Do we need to have this line now that the wait image is already published?
___
*[docker/Makefile, line 38 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01pJY0V5ZBWXAK1ci:-MX01pJY0V5ZBWXAK1cj:b-rcbvp3) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/docker/Makefile#L38)):*
> ```Makefile
> 
> .PHONY: deployable-app
> deployable-app: wait
> ```

remove `wait` dependency
___
*[src/Api/Library/Shared/Communicate/Communicate.php, line 297 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01wMNEqJSPpOHIyCY:-MX01wMNEqJSPpOHIyCZ:bl75uiw) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/src/Api/Library/Shared/Communicate/Communicate.php#L297)):*
> ```PHP
>     private static function sendTemplateEmail($to, $subject, $templateName, $vars, $website, DeliveryInterface $delivery = null)
>     {
>         $from = 'no-reply@languageforge.org';
> ```

$from is expected to be an array.  This change causes several PHP tests to fail (all in the same way):

See https://build.palaso.org/buildConfiguration/LanguageForgeDocker_PhpTests/262987

```
PHPUnit\Framework\ExpectationFailedException
CommunicateTest::testSendSignup_NoDefaultProject_PropertiesToFromBodyOk
'no-reply@languageforge.org' does not match expected type "array".
/var/www/test/php/library/shared/communicate/CommunicateTest.php:184
```


<!-- Sent from Reviewable.io -->

2021-04-01 08:21 UTC, megahirt commented on src/Api/Library/Shared/Communicate/Communicate.php
> +        $from = 'no-reply@languageforge.org';
I'm thinking this will fix the unit test failures.
```suggestion
        $from = ['no-reply@languageforge.org' => 'Language Forge'];
```

2021-04-01 19:16 UTC, longrunningprocess reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/895)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @megahirt)

___
*[.github/workflows/build-and-deploy-images.yml, line 7 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX00qQf-63rMWrzOtKT:-MXDjwUh8G1fLx2eoh7R:b-opnwcy) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L7)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

we'll want to change this to be `qa` and `live` since these two branches track our production deployments.  Good that you've been testing GA using your PR branch.  Looks like it's working well!.  If you'd prefer to change this after your PR is merged, that is fine with me.
</blockquote></details>

yep, good catch.  I'm going to simply update this trigger to look for a `build-n-publish-images` tag, that will give us the most flexibility for now.
___
*[.github/workflows/build-and-deploy-images.yml, line 49 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01c3D8bUNOJy_yE35:-MXDkNAZ729WOOPpa-ms:b-bu7zaf) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L49)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Do we need to have this line now that the wait image is already published?
</blockquote></details>

I don't suppose so, I'll remove this.
___
*[.github/workflows/build-and-deploy-images.yml, line 63 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01jns5rhVVFN4WWUk:-MXDkU8V18DzRzTzaOnq:b-896fix) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/.github/workflows/build-and-deploy-images.yml#L63)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

Do we need to have this line now that the wait image is already published?
</blockquote></details>

Done.
___
*[docker/Makefile, line 38 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01pJY0V5ZBWXAK1ci:-MXDlKdcDZRVEhd7FFYH:bq39mk6) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/docker/Makefile#L38)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

remove `wait` dependency
</blockquote></details>

hmmm, let me see if I can get those changes in here that will grab wait from Docker Hub...
___
*[src/Api/Library/Shared/Communicate/Communicate.php, line 297 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MX01wMNEqJSPpOHIyCY:-MXDr7Vr9ztXCoCtHlS7:bupa4k4) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/src/Api/Library/Shared/Communicate/Communicate.php#L297)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

$from is expected to be an array.  This change causes several PHP tests to fail (all in the same way):

See https://build.palaso.org/buildConfiguration/LanguageForgeDocker_PhpTests/262987

```
PHPUnit\Framework\ExpectationFailedException
CommunicateTest::testSendSignup_NoDefaultProject_PropertiesToFromBodyOk
'no-reply@languageforge.org' does not match expected type "array".
/var/www/test/php/library/shared/communicate/CommunicateTest.php:184
```
</blockquote></details>

yep, it never occurred to me to re-run those tests locally first, thank you fro passing along those failures.
___
*[src/Api/Library/Shared/Communicate/Communicate.php, line 297 at r1](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-MWjqCJXhQ_T14j4_27F-r1-297:-MXDrEbE73WEfIulG5LQ:b-em6y6h) ([raw file](https://github.com/sillsdev/web-languageforge/blob/778dd53e44ec302912b9f23e238de8995f4abb28/src/Api/Library/Shared/Communicate/Communicate.php#L297)):*
<details><summary><i>Previously, megahirt (Christopher Hirt) wrote…</i></summary><blockquote>

I'm thinking this will fix the unit test failures.
```suggestion
        $from = ['no-reply@languageforge.org' => 'Language Forge'];
```
</blockquote></details>

yep, that does the job, thanks!


<!-- Sent from Reviewable.io -->

2021-04-01 19:39 UTC, longrunningprocess reviewed
ok, I just test the runtime and emails are still being sent so we're gtg (aside from the TC failures but those are related to some of build config changes that are in place now.)  

I'll rebase now and see if I make TC happy again.

I'm also using the tag now to trigger image builds and a manual redeployment to the k8s environment until we're in a spot to automate CD.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-:-MXDwNmkB_IeREmtAKMQ:b-35fg0b)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @megahirt)



<!-- Sent from Reviewable.io -->

2021-04-01 20:13 UTC, longrunningprocess reviewed
unit tests are passing now, we should be gtg on this PR now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-:-MXE3LVv2MbnI9GzKgYO:b-k5ohay)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @megahirt)



<!-- Sent from Reviewable.io -->

2021-04-02 02:58 UTC, megahirt approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-languageforge/895#-:-MXFW7ES8ABcL9fMQ6Ek:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @longrunningprocess)



<!-- Sent from Reviewable.io -->

2021-04-02 02:58 UTC, merged