Select E2E tests with TEST_SPECS env var
sillsdev/web-languageforge pull request #970
Opened 2021-05-31 07:13 UTC by rmunn

Passing a `TEST_SPECS` variable to Make, either via an environment variable (`export TEST_SPECS=foo`) or as `make TEST_SPECS=foo e2e-tests` on the command line, will now select only that spec file to run. E.g.:

```bash
make TEST_SPECS=test/app/languageforge/lexicon/lexicon-new-project.e2e-spec.js e2e-tests
```

Note that the `TEST_SPECS` value should end in .js, not .ts, and should be relative to the root of the repo.

2021-05-31 07:17 UTC, rmunn commented
The value this provides is the ability to iterate over one specific file when trying to fix a flaky E2E test, so that the tests take far less time to run and you can iterate faster. To get the filename easily, in VS Code you can right-click the tab of the spec file you want to run, then choose "Copy Relative Path" from the dropdown menu. Then in a command line, type:

1. `export TEST_SPECS=`
2. Ctrl+V
3. Backspace over `.ts` and change it to `.js`
4. Enter
5. `make e2e-tests`

And now you're running only the tests in that one file. To go back to running all the tests, just run `unset TEST_SPECS` in that command prompt and then `make e2e-tests` will run all the E2E tests again.

2021-06-01 03:02 UTC, megahirt requested changes
This is really great Robin!  I had actually come up with a similar unfinished solution using "suites" instead of specs, but yours is simpler and very usable.

One requested change: can you add the instructions from this PR into the Readme.md under the appropriate section?  These instructions are really valuable.

2021-06-03 15:06 UTC, rmunn commented
@megahirt - Done, ready to be approved & merged now.

2021-06-03 15:56 UTC, megahirt approved these changes
Approved!  Thank you for including the README instructions.  I've added a small addition as well.

2021-06-03 15:56 UTC, megahirt commented on README.md
> +
I'll add the additional steps we talked about to quickly run the tests again without rebuilding.

```suggestion

To quickly re-run the tests without going through the `make build` process, you can restart the `app-for-e2e` container and run the tests as follows:
`docker-compose restart app-for-e2e && docker-compose run -e TEST_SPECS= test-e2e` where the relative path to the test spec file is optionally given after the `=` sign.
```

2021-06-10 04:36 UTC, merged